"""initial schema

Revision ID: 8670630250e7
Revises: 
Create Date: 2026-07-08 21:55:46.750516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8670630250e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- extensions needed for UUID generation + geo radius search ----
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    op.execute('CREATE EXTENSION IF NOT EXISTS cube')
    op.execute('CREATE EXTENSION IF NOT EXISTS earthdistance')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ccn', sa.String(length=20), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('facility_type', sa.String(length=200), nullable=True),
    sa.Column('legal_business_name', sa.String(length=500), nullable=True),
    sa.Column('ownership_type', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('county', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('facility_subtype', sa.String(length=200), nullable=True),
    sa.Column('operating_status', sa.String(length=50), nullable=True),
    sa.Column('closed_date', sa.String(length=30), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=300), nullable=True),
    sa.Column('source_file', sa.String(length=300), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=True),
    sa.Column('load_timestamp', sa.String(length=50), nullable=True),
    sa.Column('extra_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_city'), 'facilities', ['city'], unique=False)
    op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_facilities_state'), 'facilities', ['state'], unique=False)
    op.create_index('ix_facilities_state_type', 'facilities', ['state', 'facility_type'], unique=False)
    op.create_index(op.f('ix_facilities_zip_code'), 'facilities', ['zip_code'], unique=False)

    # ---- Dedup / identity indexes ----
    op.execute(
        "CREATE UNIQUE INDEX ix_facilities_ccn_unique "
        "ON facilities (ccn) WHERE ccn IS NOT NULL"
    )
    op.create_index('ix_facilities_dedup_hash_unique', 'facilities', ['dedup_hash'], unique=True)
    op.execute(
        "CREATE INDEX ix_facilities_geo ON facilities "
        "USING gist (ll_to_earth(latitude, longitude)) "
        "WHERE latitude IS NOT NULL AND longitude IS NOT NULL"
    )

    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('onboarding_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_care_type', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility_services',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('offers_alzheimer_dementia_care', sa.String(length=10), nullable=True),
    sa.Column('offers_hospice_care', sa.String(length=10), nullable=True),
    sa.Column('offers_ventilator_care', sa.String(length=10), nullable=True),
    sa.Column('offers_psychiatric_care', sa.String(length=10), nullable=True),
    sa.Column('offers_substance_abuse_treatment', sa.String(length=10), nullable=True),
    sa.Column('offers_hiv_care', sa.String(length=10), nullable=True),
    sa.Column('offers_rehab_services', sa.String(length=10), nullable=True),
    sa.Column('offers_adult_day_care', sa.String(length=10), nullable=True),
    sa.Column('offers_respite_care', sa.String(length=10), nullable=True),
    sa.Column('offers_home_care_services', sa.String(length=10), nullable=True),
    sa.Column('offers_traumatic_brain_injury_care', sa.String(length=10), nullable=True),
    sa.Column('offers_iv_therapy', sa.String(length=10), nullable=True),
    sa.Column('offers_pain_management', sa.String(length=10), nullable=True),
    sa.Column('offers_medical_equipment_supply', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('home_health_details',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('hh_provides_nursing_care', sa.String(length=10), nullable=True),
    sa.Column('hh_provides_physical_therapy', sa.String(length=10), nullable=True),
    sa.Column('hh_provides_occupational_therapy', sa.String(length=10), nullable=True),
    sa.Column('hh_provides_speech_therapy', sa.String(length=10), nullable=True),
    sa.Column('hh_provides_medical_social_services', sa.String(length=10), nullable=True),
    sa.Column('hh_provides_home_health_aides', sa.String(length=10), nullable=True),
    sa.Column('hh_improved_walking_mobility_pct', sa.Float(), nullable=True),
    sa.Column('hh_improved_getting_out_of_bed_pct', sa.Float(), nullable=True),
    sa.Column('hh_improved_bathing_ability_pct', sa.Float(), nullable=True),
    sa.Column('hh_improved_breathing_pct', sa.Float(), nullable=True),
    sa.Column('hh_improved_taking_medications_pct', sa.Float(), nullable=True),
    sa.Column('hh_developed_bedsores_pct', sa.Float(), nullable=True),
    sa.Column('hh_falls_major_injury_pct', sa.Float(), nullable=True),
    sa.Column('hh_started_care_on_time_pct', sa.Float(), nullable=True),
    sa.Column('hh_medication_issues_fixed_on_time_pct', sa.Float(), nullable=True),
    sa.Column('hh_functional_ability_discharge_score', sa.Float(), nullable=True),
    sa.Column('hh_info_shared_with_doctor_pct', sa.Float(), nullable=True),
    sa.Column('hh_info_shared_with_family_pct', sa.Float(), nullable=True),
    sa.Column('hh_home_discharge_success', sa.Float(), nullable=True),
    sa.Column('hh_hospital_readmission_rate', sa.Float(), nullable=True),
    sa.Column('hh_avoidable_hospitalizations', sa.Float(), nullable=True),
    sa.Column('hh_medicare_cost_vs_national_avg', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_time_preference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nursing_home_details',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('nh_total_certified_beds', sa.Integer(), nullable=True),
    sa.Column('nh_average_daily_residents', sa.Float(), nullable=True),
    sa.Column('nh_chain_affiliation', sa.String(length=300), nullable=True),
    sa.Column('nh_ccrc', sa.String(length=50), nullable=True),
    sa.Column('nh_abuse_complaint', sa.String(length=50), nullable=True),
    sa.Column('nh_special_focus_facility', sa.String(length=50), nullable=True),
    sa.Column('nh_sprinkler_system', sa.String(length=50), nullable=True),
    sa.Column('nh_health_inspection_star_rating', sa.Float(), nullable=True),
    sa.Column('nh_staffing_star_rating', sa.Float(), nullable=True),
    sa.Column('nh_quality_measure_star_rating', sa.Float(), nullable=True),
    sa.Column('nh_total_nursing_hours_per_resident_day', sa.Float(), nullable=True),
    sa.Column('nh_rn_hours_per_resident_day', sa.Float(), nullable=True),
    sa.Column('nh_lpn_hours_per_resident_day', sa.Float(), nullable=True),
    sa.Column('nh_cna_hours_per_resident_day', sa.Float(), nullable=True),
    sa.Column('nh_pt_hours_per_resident_day', sa.Float(), nullable=True),
    sa.Column('nh_staffing_level_assessment', sa.Text(), nullable=True),
    sa.Column('nh_total_nursing_staff_turnover_pct', sa.Float(), nullable=True),
    sa.Column('nh_rn_turnover_pct', sa.Float(), nullable=True),
    sa.Column('nh_administrators_left_12mo', sa.Integer(), nullable=True),
    sa.Column('nh_staff_stability', sa.String(length=300), nullable=True),
    sa.Column('nh_health_deficiencies_latest', sa.Integer(), nullable=True),
    sa.Column('nh_health_deficiency_severity_score', sa.Float(), nullable=True),
    sa.Column('nh_weighted_health_inspection_score', sa.Float(), nullable=True),
    sa.Column('nh_number_of_fines', sa.Integer(), nullable=True),
    sa.Column('nh_total_fines_usd', sa.Float(), nullable=True),
    sa.Column('nh_medicare_payment_denials', sa.Integer(), nullable=True),
    sa.Column('nh_total_penalties', sa.Integer(), nullable=True),
    sa.Column('nh_infection_control_citations', sa.Integer(), nullable=True),
    sa.Column('nh_penalty_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('saved_facilities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'facility_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute('DROP INDEX IF EXISTS ix_facilities_geo')
    op.drop_index('ix_facilities_dedup_hash_unique', table_name='facilities')
    op.execute('DROP INDEX IF EXISTS ix_facilities_ccn_unique')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_facilities')
    op.drop_table('nursing_home_details')
    op.drop_table('inquiries')
    op.drop_table('home_health_details')
    op.drop_table('facility_services')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_facilities_zip_code'), table_name='facilities')
    op.drop_index('ix_facilities_state_type', table_name='facilities')
    op.drop_index(op.f('ix_facilities_state'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_city'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
