"""
One-off dev helper: patches a freshly-autogenerated Alembic initial-schema
migration with the extensions, partial-unique indexes, and geo index that
Alembic's autogenerate cannot express on its own. Only needed when the
initial schema migration is regenerated from scratch during development;
NOT part of the runtime app.
"""
import sys
from pathlib import Path

if len(sys.argv) != 2:
    print("Usage: python3 patch_migration.py <path_to_migration.py>")
    sys.exit(1)

path = Path(sys.argv[1])
content = path.read_text()

content = content.replace(
    "def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n    op.create_table('facilities',",
    "def upgrade() -> None:\n"
    "    # ---- extensions needed for UUID generation + geo radius search ----\n"
    "    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')\n"
    "    op.execute('CREATE EXTENSION IF NOT EXISTS cube')\n"
    "    op.execute('CREATE EXTENSION IF NOT EXISTS earthdistance')\n\n"
    "    # ### commands auto generated by Alembic - please adjust! ###\n"
    "    op.create_table('facilities',",
)

content = content.replace(
    "    op.create_index(op.f('ix_facilities_zip_code'), 'facilities', ['zip_code'], unique=False)\n    op.create_table('profiles',",
    "    op.create_index(op.f('ix_facilities_zip_code'), 'facilities', ['zip_code'], unique=False)\n\n"
    "    # ---- Dedup / identity indexes ----\n"
    "    op.execute(\n"
    "        \"CREATE UNIQUE INDEX ix_facilities_ccn_unique \"\n"
    "        \"ON facilities (ccn) WHERE ccn IS NOT NULL\"\n"
    "    )\n"
    "    op.create_index('ix_facilities_dedup_hash_unique', 'facilities', ['dedup_hash'], unique=True)\n"
    "    op.execute(\n"
    "        \"CREATE INDEX ix_facilities_geo ON facilities \"\n"
    "        \"USING gist (ll_to_earth(latitude, longitude)) \"\n"
    "        \"WHERE latitude IS NOT NULL AND longitude IS NOT NULL\"\n"
    "    )\n\n"
    "    op.create_table('profiles',",
)

content = content.replace(
    "def downgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###\n    op.drop_table('saved_facilities')",
    "def downgrade() -> None:\n"
    "    op.execute('DROP INDEX IF EXISTS ix_facilities_geo')\n"
    "    op.drop_index('ix_facilities_dedup_hash_unique', table_name='facilities')\n"
    "    op.execute('DROP INDEX IF EXISTS ix_facilities_ccn_unique')\n"
    "    # ### commands auto generated by Alembic - please adjust! ###\n"
    "    op.drop_table('saved_facilities')",
)

path.write_text(content)
print(f"Patched {path}")
